import pandas as pd
import os

r = pd.read_parquet("parquet/requirements_encoded.parquet")
c = pd.read_parquet("parquet/clos_encoded.parquet")

print("=== REQUIREMENTS ===")
print(f"rows: {len(r)}")
print(f"columns: {list(r.columns)}")
print(f"dtypes:\n{r.dtypes}")
print(f"unique job_id: {r['job_id'].nunique() if 'job_id' in r.columns else 'N/A'}")
print(f"unique company (non-null): {r['company'].dropna().nunique() if 'company' in r.columns else 'N/A'}")
print(f"null company rows: {r['company'].isna().sum() if 'company' in r.columns else 'N/A'}")
print(f"embedding dim: {len(r['embedding'].iloc[0])}")
print(f"embedding sample [0:3]: {r['embedding'].iloc[0][:3]}")
print(f"file size: {os.path.getsize('parquet/requirements_encoded.parquet')/1024/1024:.1f} MB")
print()
print("=== CLOS ===")
print(f"rows: {len(c)}")
print(f"columns: {list(c.columns)}")
print(f"dtypes:\n{c.dtypes}")
print(f"unique mata_kuliah: {c['mata_kuliah'].nunique() if 'mata_kuliah' in c.columns else 'N/A'}")
print(f"embedding dim: {len(c['embedding'].iloc[0])}")
print(f"file size: {os.path.getsize('parquet/clos_encoded.parquet')/1024/1024:.1f} MB")
print()
print("=== REQUIREMENTS HEAD ===")
print(r.drop(columns=['embedding']).head(3).to_string())
print()
print("=== CLOS HEAD ===")
print(c.drop(columns=['embedding']).head(3).to_string())
